export const BOOKS_LIST_REQUEST = "BOOKS_LIST_REQUEST";
export const BOOKS_LIST_SUCCESS = "BOOKS_LIST_SUCCESS";
export const BOOKS_LIST_FAIL = "BOOKS_LIST_FAIL";

export const CATEGORY_BOOKS_FETCH_REQUEST = "CATEGORY_BOOKS_FETCH_REQUEST";
export const CATEGORY_BOOKS_FETCH_SUCCESS = "CATEGORY_BOOKS_FETCH_SUCCESS";
export const CATEGORY_BOOKS_FETCH_FAIL = "CATEGORY_BOOKS_FETCH_FAIL";

export const MY_BOOKS_FETCH_REQUEST = "MY_BOOKS_FETCH_REQUEST";
export const MY_BOOKS_FETCH_SUCCESS = "MY_BOOKS_FETCH_SUCCESS";
export const MY_BOOKS_FETCH_FAIL = "MY_BOOKS_FETCH_FAIL";

// export const BOOKS_SORT_BY_RATING_REQUEST = "BOOKS_SORT_BY_RATING_REQUEST";
// export const BOOKS_SORT_BY_RATING_SUCCESS = "BOOKS_SORT_BY_RATING_SUCCESS";
// export const BOOKS_SORT_BY_RATING_FAIL = "BOOKS_SORT_BY_RATING_FAIL";

// export const BOOKS_FIND_BY_TITLE_REQUEST = "BOOKS_FIND_BY_TITLE_REQUEST";
// export const BOOKS_FIND_BY_TITLE_SUCCESS = "BOOKS_FIND_BY_TITLE_SUCCESS";
// export const BOOKS_FIND_BY_TITLE_FAIL = "BOOKS_FIND_BY_TITLE_FAIL";

export const BOOKS_FILTER_REQUEST = "BOOKS_FILTER_REQUEST";
export const BOOKS_FILTER_SUCCESS = "BOOKS_FILTER_SUCCESS";
export const BOOKS_FILTER_FAIL = "BOOKS_FILTER_FAIL";

export const BOOK_CREATE_REQUEST = "BOOK_CREATE_REQUEST";
export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";
export const BOOK_CREATE_FAIL = "BOOK_CREATE_FAIL";

export const BOOK_DELETE_REQUEST = "BOOK_DELETE_REQUEST";
export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS";
export const BOOK_DELETE_FAIL = "BOOK_DELETE_FAIL";

export const BOOK_PHOTO_UPLOAD_REQUEST = "BOOK_PHOTO_UPLOAD_REQUEST";
export const BOOK_PHOTO_UPLOAD_SUCCESS = "BOOK_PHOTO_UPLOAD_SUCCESS";
export const BOOK_PHOTO_UPLOAD_FAIL = "BOOK_PHOTO_UPLOAD_FAIL";

export const BOOK_REVIEW_CREATE_REQUEST = "BOOK_REVIEW__CREATE_REQUEST";
export const BOOK_REVIEW_CREATE_SUCCESS = "BOOK_REVIEW__CREATE_SUCCESS";
export const BOOK_REVIEW_CREATE_FAIL = "BOOK_REVIEW__CREATE_FAIL";

export const BOOK_REVIEW_UPDATE_REQUEST = "BOOK_REVIEW_UPDATE_REQUEST";
export const BOOK_REVIEW_UPDATE_SUCCESS = "BOOK_REVIEW_UPDATE_SUCCESS";
export const BOOK_REVIEW_UPDATE_FAIL = "BOOK_REVIEW_UPDATE_FAIL";

export const BOOK_REVIEWS_FETCH_REQUEST = "BOOK_REVIEWS_FETCH_REQUEST";
export const BOOK_REVIEWS_FETCH_SUCCESS = "BOOK_REVIEWS_FETCH_SUCCESS";
export const BOOK_REVIEWS_FETCH_FAIL = "BOOK_REVIEWS_FETCH_FAIL";
