export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const LOGGED_USER_INFO_REQUEST = "LOGGED_USER_INFO_REQUEST";
export const LOGGED_USER_INFO_SUCCESS = "LOGGED_USER_INFO_SUCCESS";
export const LOGGED_USER_INFO_FAIL = "LOGGED_USER_INFO_FAIL";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

// export const LOGGED_USER_INFO_REQUEST = "LOGGED_USER_INFO_REQUEST";
// export const LOGGED_USER_INFO_SUCCESS = "LOGGED_USER_INFO_SUCCESS";
// export const LOGGED_USER_INFO_FAIL = "LOGGED_USER_INFO_FAIL";

export const PROFILE_PICTURE_UPLOAD_REQUEST = "PROFILE_PICTURE_UPLOAD_REQUEST";
export const PROFILE_PICTURE_UPLOAD_SUCCESS = "PROFILE_PICTURE_UPLOAD_SUCCESS";
export const PROFILE_PICTURE_UPLOAD_FAIL = "PROFILE_PICTURE_UPLOAD_FAIL";

export const USER_ERRORS_RESET_REQUEST = "USER_ERRORS_RESET_REQUEST";
export const USER_ERRORS_RESET_SUCCESS = "USER_ERRORS_RESET_SUCCESS";
export const USER_ERRORS_RESET_FAIL = "USER_ERRORS_RESET_FAIL";
